API Integration and Artwork module
art-institute-of-chicago/journeymaker-cms pull request #9
Opened 2024-04-11 16:56 UTC by driftingly

2024-04-18 02:38 UTC, nikhiltri approved these changes
Wow, this is a ton of work! Looks great! ⭐

2024-04-19 16:14 UTC, zachgarwood approved these changes
Nice as 🧊!

2024-04-19 16:14 UTC, zachgarwood commented on app/Support/Forms/Components/QueryArtwork.php
> +        public ?array $updateFormFields = [],
I keep forgetting that we can do this now in PHP 8. 👍

2024-04-19 16:14 UTC, zachgarwood commented on database/migrations/2024_04_08_164938_create_artworks_tables.php
> +            $table->decimal('longitude', 15, 13)->nullable();
I made the same mistake with longitude in the mobile app CMS. Unlike latitude, which ranges from -90 to 90 degrees, longitude ranges from -180 to 180, so it needs an additional significant digit in its precision.

For reference, see my migration to fix this in the mobile CMS repo:
https://github.com/art-institute-of-chicago/aic-mobile-cms/blob/develop/database/migrations/2023_12_05_001409_correct_longitude_columns.php

2024-04-19 16:16 UTC, zachgarwood requested changes
Small change to the longitude column in the migration

2024-04-19 18:34 UTC, merged